### PR TITLE
Meeting updates

### PR DESCRIPTION
**Pull request by sfunk3**
**JIRA Issue**: [EXHIBIT-106](https://jirautk.atlassian.net/browse/EXHIBIT-106)

What does this do?
==================

Addresses sub-tasks of EXHIBIT-106.

How should this be reviewed?
============================

Look at netlify preview to review style changes and confirm that they are as we discussed in our last Galston meeting.

### CODE REVIEW

**Comment by sfunk3** [comment]
@markpbaggett I know this isn't totally finished, but I say we get our progress here merged so we don't lose track of it.

**Comment by markpbaggett** [comment]
@sfunk3, because of the change to "Explore the Volume" specifically,  what if we were to email: Cathy, Emily G., and Louisa ask them to review PR deployment on Netlify.  In the email, point out the specific changes for them to pay attention to along with a link to Browse the Preview.  I say this because I expect some people may not link the "Explore the Volume" Change once they see it.  How does that sound?

**Review by markpbaggett — COMMENTED** [review]
I'm good with this as soon as we get feedback from the project team on whether they still want explore to work this way.

**Review by markpbaggett — COMMENTED** [review]
👍🏻

**Pull request merged**
