### PR TITLE
Cleanup Sass structure for exhibit customizations

### PR DESCRIPTION
**Pull request by mathewjordan**
https://jirautk.atlassian.net/browse/EXHIBIT-87

What does this do?
==================
This PR reorganizations some stray layout files and and adds them to a directory path of `sass/entity/galston/*`. Because the Exhibits repo is intended long term to house multiple exhibits, we should try and make sure that each Exhibit with styling that may not be global have it's own unique directory. The files moved were previously being added to the `sass/components/yith/layout` which is intended to be a global directory for the global Yith components only. If any styling needs to be applied to these components that is not global, it should occur in the relative entity directory.

How should this be reviewed?
============================
Does my thinking here make sense? It follows the logic originally outlined [here](https://docs.google.com/document/d/1nK1k5yPB0IpnupWwyyxASuw7Dzf9DCFYDgRsK_XiAlk/edit#heading=h.id5de1wrqnz6) where we were going to house custom code for each exhibit in a `subtheme` directory.

### CODE REVIEW

**Comment by mathewjordan** [comment]
I'm not sure what the conflict is here, but it's probably not serious. No code was changed for the `_music-pedagogy.scss` file. Happy to review together when ready to merge.

**Comment by mathewjordan** [comment]
@sfunk3, could you review this when you have a chance? It's related to https://jirautk.atlassian.net/browse/EXHIBIT-87

**Review by sfunk3 — APPROVED** [review]
Thanks for adding more organization here. Looks good.

**Review by markpbaggett — APPROVED** [review]
Looks good.  Merging.

**Review by markpbaggett — CHANGES_REQUESTED** [review]
@mathewjordan it looks like we have a few merge conflicts.  How do you all normally address these pre-merge?

**Comment by mathewjordan** [comment]
@sfunk3 I've resolved the merge issues but not we are seeing the build fail due to commit https://github.com/utkdigitalinitiatives/exhibits/commit/627c0e9f2b3f63f8ced7839b1ff63faeb8bbf8b1.

**Comment by mathewjordan** [comment]
@markpbaggett This build issue is resolved in https://github.com/utkdigitalinitiatives/exhibits/pull/15.

**Comment by mathewjordan** [comment]
@markpbaggett Netlify now build after approval and merge of https://github.com/utkdigitalinitiatives/exhibits/pull/15.

**Comment by mathewjordan** [comment]
@markpbaggett @sfunk3 merge conflicts and build issues for this are now resolved.

**Review by markpbaggett — APPROVED** [review]
Looks good to me.  Merging.

**Pull request merged**
